### ISSUE TITLE
Не работает ссылка для отправки сообщения администратору

### ISSUE THREAD

**Issue by Disasm** [vkorchagin/baraholka#18]
http://buy.fizteh.ru/cabinet/msg/write/Rocker/
```
Запрашиваемая страница не найдена.
С вопросами, предложениями и замечаниями пишите пользователю Rocker.
```

**Comment by vkorchagin** [comment]
УМВР. Ссылка может перенаправлять на форму входа/регистрации, если пользователь не вошел в аккаунт.

**Comment by Disasm** [comment]
Загадочно. Тем не менее, было именно описанное поведение. Если пользователь не залогинен, то выводится другое сообщение. Специально вкладку не закрывал, сейчас там всё ок. Во время проблем ещё сайт очень сильно шатало, может быть это каким-то чудесным образом оказало влияние.
